# Generated by Django 5.1.7 on 2025-05-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.TextField(default='No description yet.'),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='Unnamed Member', max_length=100),
        ),
    ]
